# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Pas_Simple
import Pas_Accelere
import bissection
import start

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 626)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 10, 231, 61))
        self.label.setStyleSheet("font: 48pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 751, 71))
        self.label_2.setStyleSheet("font: 48pt \".AppleSystemUIFont\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 150, 71, 61))
        self.label_3.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 280, 621, 261))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 540, 191, 41))
        self.label_9.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.label_9.setObjectName("label_9")
        self.retour = QtWidgets.QPushButton(self.centralwidget)
        self.retour.setGeometry(QtCore.QRect(700, 10, 101, 51))
        self.retour.setStyleSheet("")
        self.retour.setObjectName("retour")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(680, 370, 111, 71))
        self.clear.setStyleSheet("")
        self.clear.setObjectName("clear")
        self.b_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_1.setGeometry(QtCore.QRect(120, 220, 81, 51))
        self.b_1.setStyleSheet("")
        self.b_1.setObjectName("b_1")
        self.b_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_2.setGeometry(QtCore.QRect(310, 220, 81, 51))
        self.b_2.setStyleSheet("")
        self.b_2.setObjectName("b_2")
        self.b_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_3.setGeometry(QtCore.QRect(500, 220, 81, 51))
        self.b_3.setStyleSheet("")
        self.b_3.setObjectName("b_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 150, 121, 61))
        self.label_4.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 150, 91, 61))
        self.label_5.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Question 2"))
        self.label_2.setText(_translate("MainWindow", "la fonction : 𝑓 = 𝑥⁵ − 5𝑥³ − 20𝑥 + 5"))
        self.label_3.setText(_translate("MainWindow", "Pas fixe"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "SASSI Youssef ITS 2"))
        self.retour.setText(_translate("MainWindow", "retour"))
        self.clear.setText(_translate("MainWindow", "clear"))
        self.b_1.setText(_translate("MainWindow", "1"))
        self.b_2.setText(_translate("MainWindow", "2"))
        self.b_3.setText(_translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "Pas Acceleré"))
        self.label_5.setText(_translate("MainWindow", "Bissection"))
        self.b_1.clicked.connect(self.qu1)
        self.b_2.clicked.connect(self.qu2)
        
        
    def qu1():
        my_script = Pas_Simple.s_fixe()
        return my_script

    def qu2():
        my_script2 = Pas_Accelere.pas_acc()
        return my_script2

    def qu3():
        my_script3 = bissection.af1
        return my_script3


    
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    
    sys.exit(app.exec_())
