# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import newton
import question1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("font: 13pt \"Arial\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question_2 = QtWidgets.QPushButton(self.centralwidget)
        self.question_2.setGeometry(QtCore.QRect(480, 220, 151, 61))
        self.question_2.setObjectName("question_2")
        self.question_1 = QtWidgets.QPushButton(self.centralwidget)
        self.question_1.setGeometry(QtCore.QRect(190, 230, 161, 61))
        self.question_1.setObjectName("question_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 100, 551, 81))
        self.label.setStyleSheet("font: 36pt \"Helvetica Neue\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 420, 511, 71))
        self.label_2.setStyleSheet("font: 48pt \"Hoefler Text\";")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.question_2.setText(_translate("MainWindow", "Question 2"))
        self.question_1.setText(_translate("MainWindow", "Question 1"))
        self.label.setText(_translate("MainWindow", "Compte rendu 2 Optimisation"))
        self.label_2.setText(_translate("MainWindow", "SASSI Youssef ITS 2"))
        self.question_1.clicked.connect(self.move1)
        self.question_2.clicked.connect(self.move2)


    def move1(self):

        MainWindow3.show()
        

    def move2(self):

        MainWindow2.show()
        
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    MainWindow2 = QtWidgets.QMainWindow() 
    newton1 = newton.Ui_MainWindow()
    newton1.setupUi(MainWindow2)

    MainWindow3 = QtWidgets.QMainWindow() 
    ques1 = question1.Ui_MainWindow()
    ques1.setupUi(MainWindow3)
    sys.exit(app.exec_())
